sonar.projectKey=SP1_seliveli
sonar.qualitygate.wait=true
sonar.projectName=SP1 Time Tracking Frontend
sonar.sources=app
sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/.output/**,**/public/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
